export const ADD_PRODUCTT = "ADD_PRODUCTT";

export const DELETE_PRODUCTT = "DELETE_PRODUCTT";
export const GET_PRODUCTT_LOAD ="GET_PRODUCTT_LOAD"
export const GET_PRODUCTT_SUCCESS ="GET_PRODUCTT_SUCCESS"
export const GET_PRODUCTT_FAIL ="GET_PRODUCTT_FAIL";